// <auto-generated />
namespace QueueDodge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _11212015 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11212015));
        
        string IMigrationMetadata.Id
        {
            get { return "201511210709302_11212015"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
